#====BASIC PYTHON STUDENT RESULTE=====
def check_marks(marks):
    if marks>=90:
        return "Excellent"
    elif marks>=80:
        return "very good" 
    elif marks>=70:
        return"Good"
    elif marks>=60:
        return"Average"
    else:
        return"Needs Imrovement"
Name=input("enter student Name:")
Physics=int(input("Enter Pyhsics Marks:"))
Chemistry=int(input("Enter Chemistry Marks:"))
Biology=int(input("Enter Biology Marks:"))
Maths=int(input("Enter Maths Marks:"))
Urdu=int(input("Enter Urdu Marks:"))
English=int(input("Enter English Marks:"))
Average=(Physics+Chemistry+Biology+Maths+Urdu+English)/6
subject={
    "Physics":Physics,
    "Chemistry":Chemistry,
    "Biology":Biology,
    "English":English,
    "Urdu":Urdu,
    "Maths":Maths}
highest_subject=max(subject,key=subject.get)
lowest_subject=min(subject,key=subject.get)
print("student:", Name)
print("Average:",Average)
print("strongest subject:",highest_subject )
print("Needs Improvement:",lowest_subject)
print("overall performance:",check_marks(Average))
print("highest_subject:",highest_subject)
print("lowest_subject:",lowest_subject)
if Average<=60:
    print("suggestion:focus more  on weak subject and revise daily")
elif Average<=80:
    print("suggestion:Good progress.practice weak subject more.")
else:
   print("suggestion:Excellent progress.keep practicing consistently")




 



#====BASIC PYTHON STUDENT RESULTE=====
def check_marks(marks):
    if marks>=90:
        return "Excellent"
    elif marks>=80:
        return "very good" 
    elif marks>=70:
        return"Good"
    elif marks>=60:
        return"Average"
    else:
        return"Needs Imrovement"
Name=input("enter student Name:")
Physics=int(input("Enter Pyhsics Marks:"))
Chemistry=int(input("Enter Chemistry Marks:"))
Biology=int(input("Enter Biology Marks:"))
Maths=int(input("Enter Maths Marks:"))
Urdu=int(input("Enter Urdu Marks:"))
English=int(input("Enter English Marks:"))
Average=(Physics+Chemistry+Biology+Maths+Urdu+English)/6
subject={
    "Physics":Physics,
    "Chemistry":Chemistry,
    "Biology":Biology,
    "English":English,
    "Urdu":Urdu,
    "Maths":Maths}
highest_subject=max(subject,key=subject.get)
lowest_subject=min(subject,key=subject.get)
print("student:", Name)
print("Average:",Average)
print("strongest subject:",highest_subject )
print("Needs Improvement:",lowest_subject)
print("overall performance:",check_marks(Average))
print("highest_subject:",highest_subject)
print("lowest_subject:",lowest_subject)
if Average<=60:
    print("suggestion:focus more  on weak subject and revise daily")
elif Average<=80:
    print("suggestion:Good progress.practice weak subject more.")
else:
   print("suggestion:Excellent progress.keep practicing consistently")




 



#====BASIC PYTHON STUDENT RESULTE=====
def check_marks(marks):
    if marks>=90:
        return "Excellent"
    elif marks>=80:
        return "very good" 
    elif marks>=70:
        return"Good"
    elif marks>=60:
        return"Average"
    else:
        return"Needs Imrovement"
Name=input("enter student Name:")
Physics=int(input("Enter Pyhsics Marks:"))
Chemistry=int(input("Enter Chemistry Marks:"))
Biology=int(input("Enter Biology Marks:"))
Maths=int(input("Enter Maths Marks:"))
Urdu=int(input("Enter Urdu Marks:"))
English=int(input("Enter English Marks:"))
Average=(Physics+Chemistry+Biology+Maths+Urdu+English)/6
subject={
    "Physics":Physics,
    "Chemistry":Chemistry,
    "Biology":Biology,
    "English":English,
    "Urdu":Urdu,
    "Maths":Maths}
highest_subject=max(subject,key=subject.get)
lowest_subject=min(subject,key=subject.get)
print("student:", Name)
print("Average:",Average)
print("strongest subject:",highest_subject )
print("Needs Improvement:",lowest_subject)
print("overall performance:",check_marks(Average))
print("highest_subject:",highest_subject)
print("lowest_subject:",lowest_subject)
if Average<=60:
    print("suggestion:focus more  on weak subject and revise daily")
elif Average<=80:
    print("suggestion:Good progress.practice weak subject more.")
else:
   print("suggestion:Excellent progress.keep practicing consistently")




 



#====BASIC PYTHON STUDENT RESULTE=====
def check_marks(marks):
    if marks>=90:
        return "Excellent"
    elif marks>=80:
        return "very good" 
    elif marks>=70:
        return"Good"
    elif marks>=60:
        return"Average"
    else:
        return"Needs Imrovement"
Name=input("enter student Name:")
Physics=int(input("Enter Pyhsics Marks:"))
Chemistry=int(input("Enter Chemistry Marks:"))
Biology=int(input("Enter Biology Marks:"))
Maths=int(input("Enter Maths Marks:"))
Urdu=int(input("Enter Urdu Marks:"))
English=int(input("Enter English Marks:"))
Average=(Physics+Chemistry+Biology+Maths+Urdu+English)/6
subject={
    "Physics":Physics,
    "Chemistry":Chemistry,
    "Biology":Biology,
    "English":English,
    "Urdu":Urdu,
    "Maths":Maths}
highest_subject=max(subject,key=subject.get)
lowest_subject=min(subject,key=subject.get)
print("student:", Name)
print("Average:",Average)
print("strongest subject:",highest_subject )
print("Needs Improvement:",lowest_subject)
print("overall performance:",check_marks(Average))
print("highest_subject:",highest_subject)
print("lowest_subject:",lowest_subject)
if Average<=60:
    print("suggestion:focus more  on weak subject and revise daily")
elif Average<=80:
    print("suggestion:Good progress.practice weak subject more.")
else:
   print("suggestion:Excellent progress.keep practicing consistently")




 



